### ISSUE TITLE
Wat is de lifecycle van Haarlem Zaaktypecatalgus in tegenstelling tot deze?

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/gemma-zaaktypecatalogus#18]
Binnen gem. Amsterdam gebruiken we voor een project de ZTC-component van Haarlem: https://github.com/Haarlem/zaaktypecataloguscomponent

Het project hier is in feite een fork van dat project, hier wordt wel aan doorontwikkeld en aan dat project niet. Is het een idee om dit te consolideren, gezien we dit echt in productie willen gaan gebruiken.

**Comment by sergei-maertens** [comment]
@joeribekker @BoerBas kunnen jullie hier een uitspraak over doen?

@shazada ZTC is inderdaad een stripped-down versie van Haarlem ZTC. Ik *denk* dat deze wel weer gaan convergeren. De API-spec van deze component is wel leidend voor de standaard.

Persoonlijk zou ik vanaf deze component vertrekken in plaats van Haarlem ZTC, met dien verstande dat deze API nog niet feature-complete is.

**Comment by shazada** [comment]
@sergei-maertens Dank voor je bericht, ik zal dit intern bespreken en dan moeten we enkel een transitie doen.
Weet jij of er een impact is als we 'overspringen' naar deze versie? Of moeten we van scracht opnieuw de inrichting doen?

**Comment by sergei-maertens** [comment]
@shazada de [changelog](https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/blob/develop/CHANGELOG.rst) bevat normaal de wijzigingen, al durf ik niet te zeggen dat ik 100% ondervangen heb.

Het formaat van durations is wel aangepast - dat is nu niet meer een integerfield, maar een iso-8601 duration. Hier en daar kunnen op database-niveau ook wat date-velden naar datetime veranderd zijn (maar niet zeker uit het hoofd of dit ook in ZTC gebeurd is).

De migrations bouwen wel verder op Haarlem ZTC, dus op een cleane/lege database zou je moeten kunnen 'overspringen'. Ben benieuwd naar de ervaringen!

**Comment by joeribekker** [comment]
Ik sluit dit ticket vanwege inactiviteit en volgens mij is de vraag zelf wel beantwoord.

De Catalogi API (nieuwe naam) heeft ondertussen versie 1.0 RC bereikt. VNG API Beheer handelt het versiemanagement verder af. Dat staat o.a. hier beschreven: https://github.com/VNG-Realisatie/api-beheer/blob/master/versiebeheer.md#release-management

Open gerust een nieuw ticket als er nog vragen zijn.
