### ISSUE TITLE
error met docker en in python develop environment

### ISSUE THREAD

**Issue by henkhermsen** [VNG-Realisatie/gemma-zaaktypecatalogus#20]
Ik krijg onderstaande error?
C:\python\ztc>docker exec -it ztc_web_1 /app/src/manage.py loaddata admin_index groups
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 19, in get_by_natural_key
    ct = self._cache[self.db][(app_label, model)]
KeyError: ('oauth2_provider', 'accesstoken')

During handling of the above exception, another exception occurred:
------------------------------------------
vraag: hebben jullie een dump van een database met inhoud? daarmee kan ik beter laten zien wat je met de catalogus kunt doen.

**Comment by sergei-maertens** [comment]
@henkhermsen ik los dit even op, de fixture bevat nog gegevens van een app die verwijderd is.

**Comment by sergei-maertens** [comment]
@henkhermsen is gefixed - met een `docker-compose pull` krijg je de nieuwste `latest` getagde image binnen en moet het werken

**Comment by henkhermsen** [comment]
Thx
